- hosts: all # Alias de grupo o de servidor
# Opciones de conexión
  remote_user: root
# Tareas  
  tasks:
  
   - name: Que no esté nano
     apt: name=nano state=absent
     # MODULO: 
        # Propiedades del modulo
   - name: Que esté vim
     apt: name=vim state=present   
  
   - name: Quiero nginx
     apt: name=nginx state=present
  
   - name: También curl
     apt: name=curl state=present


# Etapa 1
#
# Inventario YAML- 3 máquinas en 1 grupo, mediante rangos numericos
# Ubuntu01 - 
# Ubuntu02 - 
# Ubuntu03<- No os lo creais

# Playbook:
# apt update
# apt upgrade
# creación de un usuario linux